### ISSUE TITLE
OMPL dependency

### ISSUE THREAD

**Issue by dysun0b10001** [APRIL-ZJU/CL-CBS#2]
Hi, I found the work depends on the OMPL library while not being mentioned in the README. To get your code to tun, I installed the OMPL library from here: https://ompl.kavrakilab.org/core/download.html, and I manually included the OMPL install path to the CMake List. Maybe consider adding this in the dependency section.  

Regards, 
Dingyi

**Comment by zijinoier** [comment]
Thanks for your interests.
This repo is indeed depends on OMPL, the recommended way is directly installed by `apt install libompl-dev`, which is described in README. However, manually install OMPL and add it to CMake path is also a feasible way.

**Comment by xifen523** [comment]
I have try `apt install libompl-dev` but it not work

**Comment by dongjh20** [comment]
I met this problem too, and i found a way. By 'whereis ompl', we can find that there is 'omplConfig.cmake' under /usr/share/ompl/cmake, just copy and rename! Then the build can be done without error.

**Comment by kintzhao** [comment]
Detail :  Because it can not found **FindOMPL.cmake**

robot@robot:~/my_code/test_git/CL-CBS/build$ cmake -DCMAKE_BUILD_TYPE=Release  ..
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindOMPL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OMPL", but
  CMake did not find one.

  Could not find a package configuration file provided by "OMPL" with any of
  the following names:

    OMPLConfig.cmake
    ompl-config.cmake

  Add the installation prefix of "OMPL" to CMAKE_PREFIX_PATH or set
  "OMPL_DIR" to a directory containing one of the above files.  If "OMPL"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/robot/my_code/test_git/CL-CBS/build/CMakeFiles/CMakeOutput.log".


robot@robot:~$ whereis ompl
ompl: /usr/include/ompl   /usr/share/ompl
robot@robot:~$ cd /usr/share/ompl/cmake
robot@robot:/usr/share/ompl/cmake$ ls
omplConfig.cmake  omplConfigVersion.cmake
robot@robot:/usr/share/ompl/cmake$ sudo cp omplConfig.cmake OMPLConfig.cmake 
robot@robot:/usr/share/ompl/cmake$ ls
omplConfig.cmake  OMPLConfig.cmake  omplConfigVersion.cmake








> I met this problem too, and i found a way. By 'whereis ompl', we can find that there is 'omplConfig.cmake' under /usr/share/ompl/cmake, just copy and rename! Then the build can be done without error.

**Comment by luohaojun** [comment]
Just use find_package(ompl REQUIRED) 
instead of
find_package(OMPL REQUIRED)

That works for me
